# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 20:46
from __future__ import unicode_literals

import Transaction.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tran_RefNo', models.CharField(max_length=20)),
                ('Tran_File', models.FileField(upload_to='uploaded_files', validators=[Transaction.models.validate_file_extension])),
                ('Date_uploaded', models.DateField(auto_now_add=True)),
                ('Tran_Paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Tran_Pend', models.CharField(choices=[('Approve', 'Approve'), ('Pending', 'Pending')], default='Pending', max_length=7)),
                ('Tran_calc', models.BooleanField(default=False)),
                ('StuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
