# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Application',
        ),
    ]
