# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('supervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Profile.Supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user_gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], verbose_name='Gender')),
                ('user_address', models.TextField(max_length=500, verbose_name='Address')),
                ('user_photo', models.FileField(default='', upload_to='', verbose_name='Profile Picture')),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Supervisor'), (2, 'Research Student'), (3, 'Coursework Student')], verbose_name='User Type')),
                ('user_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Terminated'), (2, 'Graduated')], verbose_name='Academic Status')),
                ('user_feesOwed', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Profile.supervisor', models.Model),
        ),
    ]
