# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:43
from __future__ import unicode_literals

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user_gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], verbose_name='Gender')),
                ('user_address', models.TextField(max_length=500, verbose_name='Address')),
                ('user_photo', models.FileField(default='', null=True, upload_to='', verbose_name='Profile Picture')),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Supervisor'), (2, 'Student')], verbose_name='User Type')),
                ('user_status', models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Terminated'), (2, 'Graduated')], verbose_name='Academic Status')),
                ('user_feesOwed', models.FloatField(default=0, verbose_name='Outstanding Payment')),
                ('stud_type', models.IntegerField(blank=True, choices=[(0, 'By Research'), (1, 'By Coursework')], verbose_name='Student Type')),
                ('br_title', models.CharField(default='', max_length=100, unique=True, verbose_name='Research Title')),
                ('br_progress', models.IntegerField(choices=[(-1, 'None'), (0, 'Proposal Defense'), (1, 'Work Completion Seminar'), (2, 'Thesis examination'), (3, 'Viva-voce')], default=-1, verbose_name='Research Progress')),
                ('bc_cgpa', Profile.models.MinMaxFloat(default=0.0, verbose_name='CGPA')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
