# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 14:57
from __future__ import unicode_literals

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=500, verbose_name='Area Name')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=500, verbose_name='Field Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, verbose_name='Gender')),
                ('user_address', models.TextField(max_length=500, verbose_name='Address')),
                ('user_photo', models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Profile Picture')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Student', 'Student')], max_length=10, verbose_name='User Type')),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated')], default='Active', max_length=10, verbose_name='Academic Status')),
                ('user_feesOwed', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Outstanding Payment')),
                ('stud_type', models.CharField(blank=True, choices=[('By Research', 'By Research'), ('By Coursework', 'By Coursework')], max_length=13, null=True, verbose_name='Student Type')),
                ('br_title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Research Title')),
                ('br_progress', models.CharField(choices=[('None', 'None'), ('Proposal Defense', 'Proposal Defense'), ('Work Completion Seminar', 'Work Completion Seminar'), ('Thesis Examination', 'Thesis Examination'), ('Viva Voce', 'Viva Voce'), ('Completed', 'Completed')], default='None', max_length=23, verbose_name='Research Progress')),
                ('bc_cgpa', Profile.models.MinMaxFloat(default=0.0, verbose_name='CGPA')),
                ('user_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Area', verbose_name='Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_cosupervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosupervisor', to=settings.AUTH_USER_MODEL, verbose_name='Co-supervisor')),
                ('s_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_2', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('s_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='a_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Field'),
        ),
    ]
