# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=500, verbose_name='Area Name')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=500, verbose_name='Field Name')),
            ],
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='br_progress',
            field=models.CharField(choices=[('None', 'None'), ('Proposal Defense', 'Proposal Defense'), ('Work Completion Seminar', 'Work Completion Seminar'), ('Thesis examination', 'Thesis examination'), ('Viva voce', 'Viva voce')], default='None', max_length=18, verbose_name='Research Progress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='br_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Research Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stud_type',
            field=models.CharField(blank=True, choices=[('By Research', 'By Research'), ('By Coursework', 'By Coursework')], max_length=13, null=True, verbose_name='Student Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated')], default='Active', max_length=10, verbose_name='Academic Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Student', 'Student')], max_length=10, verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='s_student_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_1', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='s_student_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_2', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='s_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='area',
            name='a_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Field'),
        ),
        migrations.AddField(
            model_name='profile',
            name='br_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Field'),
        ),
    ]
