# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20170918_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='br_field',
            new_name='user_field',
        ),
    ]
