# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20170801_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='br_progress',
            field=models.CharField(choices=[('None', 'None'), ('Proposal Defense', 'Proposal Defense'), ('Work Completion Seminar', 'Work Completion Seminar'), ('Thesis examination', 'Thesis examination'), ('Viva voce', 'Viva voce')], default='None', max_length=18, verbose_name='Research Progress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stud_type',
            field=models.CharField(blank=True, choices=[('By Research', 'By Research'), ('By Coursework', 'By Coursework')], max_length=13, null=True, verbose_name='Student Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated')], max_length=10, null=True, verbose_name='Academic Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Student', 'Student')], max_length=10, verbose_name='User Type'),
        ),
    ]
