# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20170918_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Area', verbose_name='Area'),
        ),
    ]
