# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20170806_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated')], default='Active', max_length=10, verbose_name='Academic Status'),
        ),
    ]
