# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20170918_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervise',
            name='s_student_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='s_student_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='s_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
