# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0006_auto_20170918_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervise',
            name='s_student_1',
        ),
        migrations.RemoveField(
            model_name='supervise',
            name='s_student_2',
        ),
        migrations.AddField(
            model_name='supervise',
            name='s_cosupervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_1', to=settings.AUTH_USER_MODEL, verbose_name='Co-supervisor'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='s_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_2', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='s_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
