# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20170919_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervise',
            name='s_cosupervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosupervisor', to=settings.AUTH_USER_MODEL, verbose_name='Co-supervisor'),
        ),
    ]
