# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20170920_0226'),
        ('Profile', '0005_auto_20170907_2344'),
    ]

    operations = [
    ]
