# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_auto_20170929_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_feesOwed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Outstanding Payment'),
        ),
    ]
