# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub_cred',
            new_name='credit_hour',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='stud',
            new_name='student',
        ),
    ]
