# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20170815_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, to='subject.Student'),
        ),
    ]
