# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20170815_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(null=True, to='subject.Student'),
        ),
    ]
