# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20170815_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
