# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_auto_20170816_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Student'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Subject'),
        ),
    ]
