# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20170816_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='subject.Enroll', to='subject.Subject'),
        ),
    ]
